### ISSUE TITLE
Health page layout not responsive

### ISSUE THREAD

**Issue by gitstart** [flanksource/flanksource-ui#1007]
Currently, on the health page, we have an issue where for smaller screens, the table on the far right is pushed under the filter section on the right, this makes the UI unusable and unreadable.

<img width="1285" alt="Screenshot 2023-03-21 at 10 42 14" src="https://user-images.githubusercontent.com/1501599/226605224-db295aec-68c7-4422-bba6-c964d3c14b24.png">

**Comment by mainawycliffe** [comment]
@moshloop I think we can close this one now if you are satisfied with the fixes made in this [PR](https://github.com/flanksource/flanksource-ui/pull/1501)
