### ISSUE TITLE
Add new connection setting

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#1085]
https://github.com/flanksource/duty/blob/main/schema/connections.hcl

**Comment by moshloop** [comment]
Postgres, MySQL, SQL Server:
- URL, Username (EnvVarSource), Password (EnvVarSource)

HTTP, Prometheus, Elasticsearch, Mongo, LDAP, Redis
URL,  Username (EnvVarSource), Password (EnvVarSource), Insecure TLS: (insecureTLS)

Windows:
Username (EnvVarSource), Password (EnvVarSource), Domain (properties.domain)

Google Cloud: 
Credentials (certificate)  (EnvVarSource, but with a large text area instead of field)

SFTP:
Host, Username, Password, Port

AWS:
Region: poperties.region
Profile: properties.profile
Access Key (username) (EnvVarSource)
Secret Key  (password) (EnvVarSource)
Insecure TLS: (properties.insecureTLS)

Kubernetes:
   Kubeconfig (certificate) - (EnvVarSource, but with a large text area instead of field)


Azure Devops:
  Organization: (username)
  Personal Access Token (PAT): (password EnvVarSource)



EnvVarSource should be a checkbox group, like how the authentication / scripts are handled on the http form.

Static | K8S Secret | K8S Configmap, that shows different fields:
   static:  Value text field
    configmap:  (Name, Key)
    secret:  (Name, Key)

And then returns:

   static: "Value"
   configmap "configmap://name/key"
  secret: "secret://name/key"

**Comment by moshloop** [comment]
@Prashanth-Nelli ^

**Comment by adityathebe** [comment]
@moshloop I htink we're missing Azure connection. Maybe we could also add GitHub?
