### ISSUE TITLE
SignUp Link Doesn't Exist. 

### ISSUE THREAD

**Issue by mprabs** [flanksource/flanksource-ui#1101]
The main login page has a form for signing in for the existing users but has no signup button for new users to register. 

![image](https://user-images.githubusercontent.com/29838005/235096451-b2027c33-ebcf-4954-b8fc-73f1e86aa26f.png)

There should be a button/link in the signin page to reroute to '/registration' page.

**Comment by moshloop** [comment]
This is by design, this an invite-only platform
