### ISSUE TITLE
UI version in profile version is incorrect

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#1133]

**Comment by mainawycliffe** [comment]
@moshloop I have been thinking about this and I think we can solve this easily, by changing how we do releases for the UI, instead, we can rely on the [npm version](https://docs.npmjs.com/cli/v8/commands/npm-version) command to create new versions and tags, the command will do both automatically. Then we can use the tags to create a release with the correct UI version. So basically, our release version would be something like this:

```
npm version minor | patch | major
```

The above would create a git tag version and bump package.json version, with the two matching.

We can then push the changes and kick off a publishing Github Action (triggered by tag) that will generate release notes and create a Github Release, among other things we currently do.
