### ISSUE TITLE
When you click on a connection, it shows you the modal to create a new connection instead of showing the details.

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#1140]
https://github.com/flanksource/flanksource-ui/assets/13419481/ea3e0397-c156-46c1-944b-11dacaddc916

**Comment by Prashanth-Nelli** [comment]
@adityathebe I think these are created directly on the backend. so there is type mapping mismatch which is causing the issue.

Please modify the connection types to the ones mentioned here https://github.com/flanksource/flanksource-ui/blob/main/src/components/Connections/connectionTypes.tsx#L38
