### ISSUE TITLE
Need changes when adding a responder 

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#1218]
- Frontend is still using `type` to fetch responder config. It should be renamed to `config_class`
- There's a mismatch between the responder type ("jira") and config class ("Jira") (notice the upper and lower case J). Probably needs to coordinate with backend to get this sorted.

**Comment by moshloop** [comment]
@adityathebe type is correct  config_class is mainly for grouping multiple types (EC2:Instance and Azure:VM) of the same class (VirtualMachine) together
