### ISSUE TITLE
Button improvements

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#123]
- [ ] Refactor all usage of  button html elements into a single Button class
- [ ] Externalize button colors into tailwind.config.js
- [ ] Add a loading attribute and loading text to add a spinner and disable button

**Comment by richardsaseun14** [comment]
Hello @moshloop, I want to pick this issue for my frontend (React) application to flanksource. I have forked the repo and cloned it on my local machine but I run into an error when I build for development and try to render on my browser. The error ossurs when the project tries to query `/db/person?limit=1`

Is there something else that needs to be done on my end to make the project run fully.
