### ISSUE TITLE
Gauge Component

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#133]
Create a component that can render a gauge e.g. for Memory / CPU isage
```json
{
label: "CPU",
value: 10,
max: 100
}
```

**Comment by moshloop** [comment]
Like this, 
<img width="204" alt="Screenshot 2022-09-09 at 17 58 49" src="https://user-images.githubusercontent.com/1489660/189380461-e080f04d-b24c-4bd6-9172-416c9a46bbc1.png">

But no need for the gradient - it can be a solid color

**Comment by amrendranath** [comment]
Hi, @moshloop I would like to work on this issue. Can you assign this issue to me?
