### ISSUE TITLE
Summary mismatch for components on the dashboard

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/flanksource-ui#1335]
When there are multiple severites of the same category is should like like:

{category icon} {red} {orange} {green} {gray}

i.e. combine low/medium into a single green box, and dont duplicate the category icon

**Comment by moshloop** [comment]
<img width="271" alt="Screenshot 2023-10-05 at 23 58 25" src="https://github.com/flanksource/flanksource-ui/assets/1489660/224e8dc6-914b-4557-b317-74ce143f4d45">

In the screenshot there are 3 security/shield icons and 3 badges, it should be 1 icon and 3 badges
