### ISSUE TITLE
Notifications table improvements

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#1370]
- Filter column should have ellipses 
- Rename Job Status to Status

**Comment by mainawycliffe** [comment]
@moshloop what about this:

https://github.com/flanksource/flanksource-ui/pull/1333#issuecomment-1709877696

**Comment by adityathebe** [comment]
The columns are overlapping. 

![image](https://github.com/flanksource/flanksource-ui/assets/13419481/5f4fafe3-ebfd-4e6f-af4d-b9532c3bab8d)
