### ISSUE TITLE
Topology filters

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#145]
- [x] Owner 
- [x] Labels
- [x]  Healthy
- [x] Type

**Comment by moshloop** [comment]
Add a filter bar just above the cards (Still use seperate dropdown, etc..) - 

<img width="2824" alt="Screenshot 2022-08-17 at 14 45 13" src="https://user-images.githubusercontent.com/1489660/185110595-dd5ce6d9-6a77-483f-bac8-65faf1978a1c.png">

**Comment by Prashanth-Nelli** [comment]
@moshloop I think we don't support topology filter by type as of now. so I will work on remaining filter changes.
https://github.com/flanksource/canary-checker/blob/b2fa27905fca31a2921ee447776a8a76ef4e9a59/pkg/topology/query.go#L23
