### ISSUE TITLE
Display username/password correctly when creating an agent

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/flanksource-ui#1576]
Username should TOKEN (which can be hardcoded in chart)

**Comment by adityathebe** [comment]
I think we also need to show a warning stating that the access token will not be accessible anymore once the modal is closed.

![image](https://github.com/flanksource/flanksource-ui/assets/13419481/e3da4049-b7c5-47de-8ee4-d1b67e7af9ae)
