### ISSUE TITLE
Sorting by component property does not take effect immiedatly 

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#1591]
i.e - After choosing a new property, you need to change the sort order for it to actually take effect

**Comment by mainawycliffe** [comment]
@yashmehrotra it seems like the sorting is broken on the backend, can you have a quick look:|

With the following payload:

```
id: 018cf78f-fdd0-4672-9043-3d199a1d9c7f
sortBy: memory
sortOrder: asc
```

I expect the following to returned a list of components sorted by memory, which isn't the case, as you can 4.8GB comes before 8.1 GB

![image](https://github.com/flanksource/flanksource-ui/assets/12270550/99447078-e551-44be-b478-07d501e28244)
