### ISSUE TITLE
connections: opening a "folder" connection opens up the "Select Connection Type" modal instead of the edit modal

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#1659]

**Comment by adityathebe** [comment]
seems like we haven't added local folder form at all. I created the connection with a CRD.

**Comment by mainawycliffe** [comment]
@adityathebe which fields should we use for the folder connection?

**Comment by adityathebe** [comment]
@mainawycliffe just the connection name, namespace & path field _(stored to properties.path)_
