### ISSUE TITLE
Notifications dropdown doesn't show the connection

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#1810]
This is because notifications saved with crds use the connection string whereas the dropdown options use the connection id.

**Comment by adityathebe** [comment]
> @adityathebe do we have an example of this?

Create one for you. 
https://incident-commander.demo.aws.flanksource.com/settings/notifications

See the one with receipient = check-alerts

**Comment by mainawycliffe** [comment]
Thanks.

Can the value be edited? Or can the notification be edited? Or do we just to show the connection details without worrying about editing the notification?

**Comment by adityathebe** [comment]
> Thanks.
> 
> Can the value be edited? Or can the notification be edited? Or do we just to show the connection details without worrying about editing the notification?

I don't think we should be able to edit notifications created by a CRD.

If the connection dropdown could somehow take two values then that would solve it. But I doubt that's possible.

**Comment by mainawycliffe** [comment]
If crd generated, we could show the notifications string instead of the dropdown for CRD notifications. Other than this, is there another way to know if a notifcations is created by a CRD?
