### ISSUE TITLE
Cannot paste into the spec fields

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#1843]
I tried pasting a spec into the Team spec field and couldn't paste anything.

**Comment by mainawycliffe** [comment]
@adityathebe can you give me an example spec that failed?

**Comment by adityathebe** [comment]
> @adityathebe can you give me an example spec that failed?

This was the behavior for all the spec.

**Comment by mainawycliffe** [comment]
> > @adityathebe can you give me an example spec that failed?
> 
> This was the behavior for all the spec.

@adityathebe I meant the spec you tried to paste

**Comment by adityathebe** [comment]
@mainawycliffe I don't remember which one it was. But anything you try to paste will not work.

**Comment by moshloop** [comment]
@adityathebe is this still an issue for you ?

**Comment by adityathebe** [comment]
@moshloop @mainawycliffe yes, still an issue for me. 

I tried pasting a playbook spec and it had no effect.

**Comment by mainawycliffe** [comment]
@adityathebe can you record a loom for this, it would be very helpful

**Comment by adityathebe** [comment]
> @adityathebe can you record a loom for this, it would be very helpful

discussed in standup. It was happening only on Brave browser.
