### ISSUE TITLE
Config Viewer - Show history table

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#188]
Based on config_changes

**Comment by richardsaseun14** [comment]
@moshloop I would need more details for this issue. Will this render on its own page or for individual configs.

**Comment by richardsaseun14** [comment]
So how do I get the config_changes?

**Comment by richardsaseun14** [comment]
@moshloop the config item and config changes endpoint doesn't return any data at the moment. Is there a way around this because it's blocking my progress

**Comment by ciju** [comment]
Part of https://github.com/flanksource/flanksource-ui/pull/255
