### ISSUE TITLE
Use `health` instead of `status` in config details

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#1883]
An unhealthy config is shown as green.

![image](https://github.com/flanksource/flanksource-ui/assets/13419481/3b982e05-0cbb-4b9e-90a3-c9827ed98725)

We have added a new `health` column with possible values
- healthy
- unhealthy
- warn
- unknown
- and possibly null

Also we might need to have a display for `ready` as well @moshloop

**Comment by moshloop** [comment]
@adityathebe - I think we might need to update the config_details view first

**Comment by adityathebe** [comment]
@moshloop updated
