### ISSUE TITLE
Dropdowns / Selects popup should grow to up to 2x to fit selections

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#200]

**Comment by serberm** [comment]
@moshloop  this dropdown/select width? Currently, it's min-width value is 200px. I think that 300px is good instead of 400px.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/44756400/187459121-9e26d013-12f7-4b18-9a26-7a83c7c2d6aa.png">
