### ISSUE TITLE
incorrect age for checks

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#2119]
![image](https://github.com/user-attachments/assets/7077efcd-b975-4e36-a100-fccacb100c94)

**Comment by mainawycliffe** [comment]
@adityathebe can you confirm this has been fixed? Looks okay

![image](https://github.com/user-attachments/assets/5787751a-bba2-4f9e-bb1d-cc79583a92e4)

**Comment by adityathebe** [comment]
@mainawycliffe It actually happens to be a timezone issue. 

My local postgres saves in my timezone (+5:45, hence I see `in 5 hours`) but the frontend doesn't handle it. I think we can close this as we'll always save in UTC.

cc @moshloop
