### ISSUE TITLE
Layout issue for messages:

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#22]
<img width="965" alt="Screenshot 2021-09-06 at 13 02 44" src="https://user-images.githubusercontent.com/1489660/132207886-f9f75752-e49f-4b9d-8aac-72ec489a11b7.png">

**Comment by johnflank** [comment]
@moshloop should be resolved in this PR: https://github.com/flanksource/flanksource-ui/pull/23

deploy preview: https://deploy-preview-23--goofy-euclid-75956c.netlify.app/canary
