### ISSUE TITLE
Resource Selector Dropdown Freezes with Large Number of Items

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#2220]
Probably switch to `react-windowed-select`

**Comment by moshloop** [comment]
@mainawycliffe are not limiting the results to 100 ?

**Comment by moshloop** [comment]
Can we create correspondending backend issue to apply limits ?

**Comment by mainawycliffe** [comment]
@moshloop I had created a corresponding issue on duty https://github.com/flanksource/duty/issues/998
