### ISSUE TITLE
notifications_summary should display error on the notification

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#2306]

**Comment by mainawycliffe** [comment]
@adityathebe we currently have this, maybe we can offer an indication there is an error for the notification

![image](https://github.com/user-attachments/assets/4239720b-93b9-4534-9a49-3a4419123db6)

**Comment by adityathebe** [comment]
@mainawycliffe there are two different source of error
- errors encountered previously when sending notifications _(we currently show this)_
- errors in the notification itself. This blocks all future notifications _(we need to display this)_

![image](https://github.com/user-attachments/assets/1dae65ef-71cb-44c4-8cb7-ea45bf0fe69f)
