### ISSUE TITLE
Right clicking anywhere on the notification send history table refreshes the page

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#2323]

**Comment by mainawycliffe** [comment]
@adityathebe is this still an issue? I can't reproduce it on my end

**Comment by adityathebe** [comment]
@mainawycliffe I can still reproduce this

Here's the stack trace if it helps
![image](https://github.com/user-attachments/assets/2f47511a-5487-47b4-b098-b5fe6cc75488)

**Comment by mainawycliffe** [comment]
@adityathebe, is this refresh triggered when you right-click on the tab content or re-focus the tab? Like devtools or move to another tab?

**Comment by adityathebe** [comment]
https://github.com/user-attachments/assets/e7087e6a-2377-48e3-91d7-2fca8e382fa9

@mainawycliffe 
Looks like the behavior has changed. I was able to consistently trigger the refresh when right cliking but now it only happens on the first right click.

**Comment by mainawycliffe** [comment]
Maybe the issue has been fixed, as I have been working on the notifications and tables for the last few weeks. I think the right doesn't trigger the first refresh. However, moving to the dev tools and back (for some reason, React Query treats this as a window refocus) will trigger a refresh for any active queries unless disabled for a specific query or globally. I'm not sure if we want to keep this behavior, but it's useful to get an automatic refresh after being away for a while.

**Comment by adityathebe** [comment]
yeah looks like it's fixed.

> However, moving to the dev tools and back (for some reason, React Query treats this as a window refocus) will trigger a refresh

that does seem to be the case.
