### ISSUE TITLE
Refresh handling 

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#364]
- Ensure every page has a refresh button in the top right
- The loading indicator should only show on the first load of the page, not subsequent refreshes - this includes navigating between tabs. 
-

**Comment by Prashanth-Nelli** [comment]
@moshloop if we don't show loader when navigate between tabs. There will be a blank screen shown before actual data gets loaded. Is this fine ?.

Or 

you want to me to persist state across tab navigations and load previous data instead of fresh api call.

**Comment by moshloop** [comment]
@Prashanth-Nelli ideally we persist the state between tabs, and then trigger a refresh
