### ISSUE TITLE
Config Detail v2.0

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#460]
- [ ] Add name / dates / labels etc into main page (it only shows the actual JSON config at the moment)
- [ ] Add a panel  showing all analysis (with description and age)
- [ ] Add a panel with related config items (icon and name)
- [ ] Add a panel with related components (icon and name)

**Comment by moshloop** [comment]
![Mockups drawio](https://user-images.githubusercontent.com/1489660/192767476-8da8ba93-4cc8-42d1-ad28-abcd2708d0f6.png)

**Comment by mainawycliffe** [comment]
@moshloop Quick question: I assume this data will come from the JSON content inside the viewer?

**Comment by moshloop** [comment]
@mainawycliffe - no this is coming from separate tables 

See the OpenAPI schema here: https://incident-commander.canary.lab.flanksource.com/config/db/ which you can view using editor.swagger.io

The tables in question are config_analysis, config_changes, config_relationships 

From a side panel design you can use something similar to this: 


![Master-Detail Cards](https://user-images.githubusercontent.com/1489660/193057815-070ca1b9-88d8-4e15-bcd2-c7eb4eddfa89.png)

**Comment by mainawycliffe** [comment]
Another question, in terms of Config Changes, Related Configs and Related Components, do we want to display a table with age or what details do we display for each on their individual panel?

**Comment by moshloop** [comment]
Related configs and components would be Icon and name only
Changes would be icon, name, count and age

**Comment by moshloop** [comment]
@mainawycliffe  Icon would come from the change_type, and then name would be summary (if specified) or change_type
age would come from created_at, and count you can leave out as it still needs to be added to the api
