### ISSUE TITLE
Add remote dropdowns

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#478]
With icons:

* Config type -  `/db/config_types` (switch on config list page) 
* Analysis type /db/analysis_types`
* Change type -  `/db/changes types`

**Comment by mainawycliffe** [comment]
@moshloop The above are filter controls on the config page, if I am not mistaken?

![image](https://user-images.githubusercontent.com/12270550/201654225-19757722-6a5b-468f-89a1-cae2620f52c5.png)
