### ISSUE TITLE
Health page state should persist through navigating to other pages

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#479]
e.g. Hide Passing

**Comment by gitstart** [comment]
@moshloop I would like to pick this up

**Comment by gitstart** [comment]
> e.g. Hide Passing

Hi @moshloop, As we were spec'ing the issue, we discovered that also other tabs have issues persist state through navigation, including `Topology`, `Logs`, `Config`, and `Incidents`. We were wondering if you would prefer a more generic solution that could maintain the state of other pages within a `session`. 

Please let us know your thoughts on this. Thanks
