### ISSUE TITLE
Implement query caching

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#530]
We need to decide on whether to use react-query or swr or other ?

The first use case is for caching component id -> name, type, icon - especially for breadcrumbs, related items etc..

We would also want to implement nested caching e.g. in definition of done, first render items without status from query cache, and then render with updated status using a shorter cache e.g. < 10s

@Prashanth-Nelli @mainawycliffe  What are your thoughts ?

**Comment by mainawycliffe** [comment]
This would be great. Probably would go with react-query, it's quite configurable and feature-rich and is already set up with the project my experience with it so far from a caching perspective has been great and it seems to be getting even wider adoption by different communities outside react.

**Comment by Prashanth-Nelli** [comment]
- api query caching is implemented for the below scenarios as asked in the issue.
   - breadcrumbs, definition of done evidence views, filters, peoples query used in mention list.

so closing this issue.
