### ISSUE TITLE
Config list - filter by tag

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#540]

**Comment by Prashanth-Nelli** [comment]
@moshloop I don't see labels data in the config api `/api/configs_db/configs` response.

**Comment by Prashanth-Nelli** [comment]
@moshloop we already have tag filter implemented. Let me know whether I should close this ticket or not.

<img width="1622" alt="Screenshot 2022-11-15 at 6 55 21 PM" src="https://user-images.githubusercontent.com/7310975/201930896-71115815-d631-4d03-af05-06aceaa7c226.png">
