### ISSUE TITLE
Config List - Paginate (and remote sort/filter)

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#551]

**Comment by Prashanth-Nelli** [comment]
@moshloop what is mean by `Paginate (and remote sort/filter)`.

This is my understanding of the above title
- add support for pagination
- remove client side sort & filter functionality offload it to backend.

**Comment by moshloop** [comment]
@Prashanth-Nelli correct

**Comment by Prashanth-Nelli** [comment]
issue is fixed in the PR #702
