### ISSUE TITLE
Redirect users to login page, if not logged in and vice versa

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#577]
Currently, the UI fails if you try and access a page expecting you to be authenticated, as shown below: 

![image](https://user-images.githubusercontent.com/12270550/201610812-06f56681-e5a3-483d-aa1a-c0ac02f7c8c5.png)

We need to implement Route redirects if the user isn't logged in or show a login modal in place. The people endpoint returns a 401; then we should take the user through the sign-in flow and store the previous URL as part of the URL so that we can redirect them back.

On the other hand if the user is logged in, and tries to access login page, the user should be redirected to the homepage of the UI, with login access, as they don't have login in again. The alternative to this, is to log them out.

@moshloop and @Prashanth-Nelli, what do you think?

**Comment by Prashanth-Nelli** [comment]
- We already have the functionality of redirecting the user to login page when the session is expired during loading (not working for some reason).
- Session expiry during app usage or after some idle time is not handled right now. 
- we also need to look into token refresh case as well.
- ory provides `return_to` query param which can used to redirect to the page that the user is trying to access before login.

**Comment by mainawycliffe** [comment]
So, we should be using Axios because of the interceptor not fetch?

**Comment by Prashanth-Nelli** [comment]
We can use any of them but as we already decided go with axios we need to maintain the consistent.

**Comment by mainawycliffe** [comment]
Cool, I will start switching to Axios.

**Comment by Benmuiruri** [comment]
Hi Team, I have cloned the repo, tried to load the UI but I got a similar error. 
![Screenshot from 2022-11-23 13-47-54](https://user-images.githubusercontent.com/2597305/203535362-1f8d9d18-6d69-43ce-a6b4-d61e8d2d4489.png)

**Comment by mainawycliffe** [comment]
Hey @Benmuiruri, sorry for the delayed response. You need to comment out `# NEXT_PUBLIC_WITHOUT_SESSION=true` in your `env.local`, this should redirect you to login page, where you can create an account and login.

**Comment by Prashanth-Nelli** [comment]
@Benmuiruri I have updated the readme with local setup details. Please follow that and let me know if you face any issues during that.

**Comment by Benmuiruri** [comment]
Hi @mainawycliffe , thanks I was able to get it to work thanks to Moshe's clarification. 

I wanted to suggest updating the README to make it clearer, but I see @Prashanth-Nelli has done that. 

Good stuff, Prashanth!
