### ISSUE TITLE
[Authentication] Skip whoami calls for /kratos/self-service endpoints

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/flanksource-ui#595]
Account recovery links are being redirected to the login page
![image](https://user-images.githubusercontent.com/5863972/203233629-ef1bd3cf-c73b-4ae9-88a8-390ce933543d.png)

**Comment by Prashanth-Nelli** [comment]
This issue can be fixed from backend by using the proper Kratos & ui redirection url's. so closing this as there are no changes at the front end side.
