### ISSUE TITLE
Unable to start project because of api failure

### ISSUE THREAD

**Issue by ericobi** [flanksource/flanksource-ui#626]
![image](https://user-images.githubusercontent.com/52289096/206461687-401ca93e-38dd-43fe-bfc0-44420ea06c42.png)

I am not able to register my account in registration page because of ory api returns 500 Internal Server Error.

**Comment by Prashanth-Nelli** [comment]
Hi @ericobi, We have documented the local setup details in readme.md file. Please follow that for setting up flanksource-ui locally.

**Comment by Prashanth-Nelli** [comment]
closing this issue as this is not reproducible.
If you face the issue again. Please include steps to reproduce the issue and reopen it.
