### ISSUE TITLE
In Logs Table, Component dropdown should show none instead of all

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#656]
Since we don't show all logs but rather one per component, the default entry should switch to none instead of all

![image](https://user-images.githubusercontent.com/12270550/208124091-a0b746f7-1ca6-429c-b326-7557832c5892.png)

**Comment by DesmondSanctity** [comment]
Hello @mainawycliffe I want to raise a PR for this, can I go ahead??

**Comment by mainawycliffe** [comment]
@DesmondSanctity feel free to go ahead
