### ISSUE TITLE
Change Details improvements

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#687]
- Increase the size of the dialog
- Changes == null, don't show anything
- s/Age/Date/ and use timestamp format
- remove name in the body
- Created By label size is not consistent 
- Refactor the key/labels into the DescriptionCard with a `labelStyle=top columns=4` the use of description in topology details would map to  `labelStyle=left` which becomes the default

**Comment by Prashanth-Nelli** [comment]
config change details improvements are covered in the PR #680
