### ISSUE TITLE
Resource Editor - Use schemas

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#690]
We can make the experience a bit better by allowing autocomplete and validation for the spec field via Monaco Editor; from my initial research, this seems possible via plugins like this: https://github.com/remcohaszing/monaco-yaml. 

It might be a good idea for the future and a step in between having a visual editor, or in conjunction with the visual editor.

What do you think @moshloop

**Comment by moshloop** [comment]
e.g. https://incident-commander.canary.lab.flanksource.com/api/schemas/canary.schema.json  - the schemas are here: 
https://github.com/flanksource/duty/tree/main/schema/openapi
