### ISSUE TITLE
Config Viewer - Default to YAML

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#692]
Currently also configs are stored in JSON, however, we should convert them to YAML when viewing as we do for the Settings page specs 

e.g. https://incident-commander.canary.lab.flanksource.com/configs/0184f51a-ae04-a367-3257-3c4d86e744cd

**Comment by zzz1ck** [comment]
looking

**Comment by zzz1ck** [comment]
<img width="444" alt="config-preview" src="https://user-images.githubusercontent.com/1412629/213432736-07d79f74-a73a-4da8-b6a8-bfed54d3610e.png">

@moshloop requested changes should be applied to only one instance of preview config or for all preview code functionality within the Configs Details page?

aka
<img width="377" alt="detailed-config-changes-preview" src="https://user-images.githubusercontent.com/1412629/213432744-77065703-0b18-452f-98eb-861b23327951.png">
<img width="1007" alt="detailed-config-diff-preview" src="https://user-images.githubusercontent.com/1412629/213432747-86ccaa01-c1ca-41cb-9879-c150a09e4f94.png">

**Comment by moshloop** [comment]
@zzz1ck I think to all of them

**Comment by zzz1ck** [comment]
https://github.com/flanksource/flanksource-ui/pull/767
