### ISSUE TITLE
Dropdowns should always have a white background

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#694]

**Comment by moshloop** [comment]
<img width="720" alt="Screenshot 2022-12-29 at 09 41 57" src="https://user-images.githubusercontent.com/1489660/209919539-8d114be5-dfd5-466b-aada-67d5bfa18be6.png">

**Comment by moshloop** [comment]
+ Ensure that the styling only occurs in the component and not in usages of the component

**Comment by zzz1ck** [comment]
@moshloop https://github.com/flanksource/flanksource-ui/pull/699
