### ISSUE TITLE
Config Page - Remove ConfigLayout

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#696]
The config pages has its own custom layout, this is not necessary it interferes with the back button - Remove the custom layout and make it consistent with the other pages.

**Comment by mainawycliffe** [comment]
@moshloop I think I removed this and fixed the navigation issues unless I missed something.

**Comment by moshloop** [comment]
@mainawycliffe  There are nested routes on the configs page: 

https://github.com/flanksource/flanksource-ui/blob/main/src/App.tsx#L144

As well as a custom layout: 

https://github.com/flanksource/flanksource-ui/blob/main/src/components/ConfigsPage/ConfigLayout.tsx

both of these should be removed, the config page should be no different to the logs or incident pages.

**Comment by mainawycliffe** [comment]
@moshloop Been thinking, NextJS is introducing Nested Layout for routes, may be we can utilize this somehow as part of a broader migration to NextJS:

https://daily-dev-tips.com/posts/next-13-nested-layouts/
https://nextjs.org/blog/layouts-rfc
https://beta.nextjs.org/docs/routing/pages-and-layouts

**Comment by moshloop** [comment]
@mainawycliffe  I would rather fix this first as the back button is really broken in the config page which impacts the UX and demos. 

I also don't see why we need nested layouts to begin with
