### ISSUE TITLE
Switch incident panels to collapsible panel with icons

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#703]
+ Add buttons field on the panel

**Comment by DesmondSanctity** [comment]
I want to work on this issue but I do not understand the requirements. Hi @moshloop can you attach a screenshot or a little explanation. Thanks

**Comment by moshloop** [comment]
@DesmondSanctity Currently the incident detail page sidebar has different styling to the topology and config detail sidebars - we want to make them more consistent and use the same underlying styling components.

**Comment by DesmondSanctity** [comment]
Got it. Will check it
