### ISSUE TITLE
Topology Breadcrumb is wrong

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#725]
This is the breadcrumb of the topology page of the default page, no topology selected (https://incident-commander.canary.lab.flanksource.com/topology?sortBy=status&sortOrder=desc), and it has a detailed breadcrumb.

![image](https://user-images.githubusercontent.com/12270550/212350312-965248da-3b26-4e4f-a238-26c999228bb1.png)

**Comment by DesmondSanctity** [comment]
Hi @mainawycliffe . I fixed this for when no topology selected, it now shows only **Topology** without those other items.

![image](https://user-images.githubusercontent.com/51109125/212800226-19f75f5c-2ca2-4ad4-8a2c-3e5a9270bddd.png)

For this case in this picture below, is it correct too? Only one topology selected but the breadcrumb link is pointing through other ids to the topology. 

![image](https://user-images.githubusercontent.com/51109125/212799409-bd5d1d8e-656c-4b67-a0a2-81f819a332ec.png)
