### ISSUE TITLE
System Viewer

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#75]
See: 
<img width="1051" alt="Screenshot 2021-11-25 at 15 02 03" src="https://user-images.githubusercontent.com/1489660/143446673-b795fbe6-be18-4fad-9f87-4a4d05836d13.png">
And the data:

https://gist.github.com/moshloop/dd584c0e2f803a3b05f5d2318479d703

**Comment by moshloop** [comment]
A similar type of implementation in Vue is here: https://github.com/flanksource/karina-ui/blob/master/src/components/IndicatorCard.vue

**Comment by johnflank** [comment]
Leaving this here for future reference:
https://www.figma.com/file/voV1BCPxEGAYpmQhJwa0nU/flanksource-ui%2Fsystem-viewer-layout
