### ISSUE TITLE
Logs page search query filter not working as expected

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#752]
When you enter any term in the search field, the logs still get returned without any indication of being filtered down.

**Comment by usmailaabdoul** [comment]
Hi @mainawycliffe could you walk me through how to get some logs so i can try to reproduce this bug, current i don't have any logs to test with.
<img width="1285" alt="Screenshot 2023-03-21 at 10 23 45" src="https://user-images.githubusercontent.com/50529081/226564390-3b2bef7e-49cd-4f84-9c68-9482f6b6e327.png">
