### ISSUE TITLE
Add action bar in topology sidebar

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#781]
i.e.all actions in the burger menu should be actions at the top of the of the sidebar.

**Comment by mainawycliffe** [comment]
Is this what you meant?

![215704268-a89704a8-bd07-45b5-8b3f-399ad0f429c6](https://user-images.githubusercontent.com/12270550/215975765-6db99f4a-766e-44bd-b3c5-c95135ada735.png)
