### ISSUE TITLE
Incident Details Side panels taking up space even when they don't need to

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#812]
If this is intentional, may be add a vertically centered No details found or Collapse if they are empty.

![image](https://user-images.githubusercontent.com/12270550/220016273-da297ad2-6fcd-4db4-9dc5-137b610248fa.png)

**Comment by Prashanth-Nelli** [comment]
I feel having some context provided at each section level when there is no data will help users compared to just showing `there is no data` message.

**Comment by moshloop** [comment]
- We should resize all the panels if one of them is collapsed
- Reduce the definition of done and responders panels to half the size of the others.
