### ISSUE TITLE
Config List Tags Column Looks Bad For Some Single Items

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#829]
![image](https://user-images.githubusercontent.com/12270550/221573062-ba3505af-a08c-448d-bd3e-96b3e33eca3a.png)

**Comment by Prashanth-Nelli** [comment]
@mainawycliffe This is being handled in the PR https://github.com/flanksource/flanksource-ui/pull/821

**Comment by mainawycliffe** [comment]
@Prashanth-Nelli Great 👍
