### ISSUE TITLE
Switch to formik

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#858]
We are going to start building lots of forms and I think Formik will reduce much of the unnecessary boilerplate - wdyt ?

**Comment by moshloop** [comment]
Create field wrappers for

- [ ] Select
- [ ] Toggle

**Comment by Prashanth-Nelli** [comment]
We already have some forms & re usable controls built using the `react-hook-form` library api.
* `Formik` & `react-hook-form` both provide same functionality. 
* But in terms of performance & library size `react-hook-form` is better compared to `Formik`.

**Comment by moshloop** [comment]
The problem with react-hook form is that it is extremely verbose, you need to manage each and every field value with multuple lines of code - 

We need to optimize for getting as many forms built as quickly as possible, not library size or UI performance on forms.

**Comment by Prashanth-Nelli** [comment]
sure
