### ISSUE TITLE
Namespace label should be visible even in case text is too big

### ISSUE THREAD

**Issue by Kaitou786** [flanksource/flanksource-ui#87]
When having a large name/description for the check the namespace tag when viewing across all seems to be truncated:
See below:
![Screenshot 2021-12-23 at 4 27 51 PM](https://user-images.githubusercontent.com/36669272/147230911-3c02daf2-17a6-4d90-94e3-f50a3b561cbe.png)

In such cases the description can be truncated but we should still preserve the namespace tag in the row

**Comment by ciju** [comment]
Is this still relevant?
