### ISSUE TITLE
Check Status Table fixes

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#919]
- The table should be full height, with the pager at the bottom - i.e. the whiteshapce is between the last row and the pager, not between the pager and the footer
- It seems to be sending to many queries:
- 
<img width="1170" alt="Screenshot 2023-03-10 at 16 48 27" src="https://user-images.githubusercontent.com/1489660/224346986-b22c4275-e0da-466b-bca2-feee9e5b369f.png">

- The paging buttons don't appear to work

**Comment by gitstart** [comment]
@moshloop I would like to pick this up

**Comment by gitstart-instrumental** [comment]
@moshloop would like to know, what page on the application i can find this issue

**Comment by seunexplicit** [comment]
@moshloop would like to know, what page on the application i can find this issue

**Comment by gitstart** [comment]
Hi @moshloop @Prashanth-Nelli, on what page can this affected table be found?
