### ISSUE TITLE
Add reliability analysis type

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#920]
![noun-time-guard-4271542](https://user-images.githubusercontent.com/1489660/224350823-f480fb4f-c595-4f64-bf3a-61e994c90382.svg)

**Comment by DesmondSanctity** [comment]
@moshloop this icon isn't in any of the react-icons library. Can I use something similar(check draft PR)? Or find a way to configure the svg to accept the size and color parameters?

Thanks
