### ISSUE TITLE
Add missing page titles

### ISSUE THREAD

**Issue by mainawycliffe** [flanksource/flanksource-ui#929]
This issue will track pages, whose titles are missing:

- [x] Job History Pages -> Will be fixed in #857
- [ ] Details Pages for Settings i.e. Settings -> Component -> Component Item
- [ ] Config Insights Page -> Configs -> Insights Tab

**Comment by aayushdura** [comment]
![image](https://user-images.githubusercontent.com/58044533/226406432-f11d5ab9-a136-4ae7-973b-92276e0061f0.png)
@mainawycliffe  these id's used instead of the titles used in breadcrumbs you mean?

**Comment by gitstart** [comment]
@mainawycliffe I would like to pick this up. Cc @moshloop

**Comment by mainawycliffe** [comment]
@aayushdura No, not the breadcrumbs but HTML Page Titles, something like this https://github.com/flanksource/flanksource-ui/blob/23ce3d6376b076de27b57aaae404a057025275ad/src/components/JobsHistory/JobsHistorySettingsPage.tsx#L28

**Comment by aayushdura** [comment]
> 

Sure, @mainawycliffe , Also about the breadcrumbs too, it would be nice if names are shown instead of those ids.

**Comment by mainawycliffe** [comment]
@aayushdura yeah, that would be nice, but probably a more significant task that would require a different issue to track it.
