### ISSUE TITLE
When creating a canary from UI, bad spec gets saved

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/flanksource-ui#940]
Steps:
- Create a new canary at: https://incident-commander.canary.lab.flanksource.com/settings/canaries
- In spec field, input anything random

Expected behaviour: since openapi check fails, it should not save the spec

Actual behavior: Empty spec saved

**Comment by yashmehrotra** [comment]
Same for topology and other UI added specs from settings

**Comment by mainawycliffe** [comment]
@moshloop should we close this in favor of #1049?
