### ISSUE TITLE
Logs page breadcrumb doesn't have icon

### ISSUE THREAD

**Issue by Prashanth-Nelli** [flanksource/flanksource-ui#976]

**Comment by gitstart** [comment]
@moshloop @Prashanth-Nelli I would like to pick this up

**Comment by Prashanth-Nelli** [comment]
this is being fixed in the PR https://github.com/flanksource/flanksource-ui/pull/1053

**Comment by Prashanth-Nelli** [comment]
closing this as this issue is fixed in #1053
