### ISSUE TITLE
Card width is a slider but does not seem like it, there should be a darker line that we can slide across

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/flanksource-ui#980]
![image](https://user-images.githubusercontent.com/5863972/226571206-4321affe-8e1c-4d41-9b91-b3bf4ec73eb0.png)

**Comment by mainawycliffe** [comment]
@yashmehrotra can you confirm this is still an issue on your side?

![image](https://github.com/flanksource/flanksource-ui/assets/12270550/a31b73d9-ca06-4700-bc93-f8d8286e7a5f)

**Comment by yashmehrotra** [comment]
Yeah, still there for me

Browser: Mozilla Firefox
