### ISSUE TITLE
[Topology] Health filter doesn't cover all possibilities?

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#983]
![image](https://user-images.githubusercontent.com/13419481/226571623-884a682b-1773-42a9-a260-7a1d4b8c87c5.png)

### Cluster-2 doesn't fall into any health filter

![image](https://user-images.githubusercontent.com/13419481/226571700-323ba645-23ea-4515-853b-526c14a4022f.png)

![image](https://user-images.githubusercontent.com/13419481/226571726-8fa485af-6fc6-4e87-b08d-e73fa81fee6a.png)

![image](https://user-images.githubusercontent.com/13419481/226571747-3e5022d6-c42f-46d2-952f-07d825c07427.png)

**Comment by moshloop** [comment]
Switch the health / teams list returned via the topology api
